### ISSUE TITLE
Make the upper navbar mobile responsive

### ISSUE THREAD

**Issue by Advaith-RN** [acmpesuecc/hyper-soar#1]
This repo uses tailwind-css. For this issue, you need to make the navbar collapsible in mobile-view.

_Alternative solutions to a simple collapsible navbar will net in bonus bounty points :)_

### Maintainer Name
Advaith Rajan Nair

**Comment by aishwarya-mali** [comment]
@Advaith-RN Can I work on this issue?

**Comment by PandaTGOS** [comment]
Can I get assigned to this ?

**Comment by kavs2803** [comment]
heyy can i work on this?

**Comment by sid-nc** [comment]
can i get assigned

**Comment by pratham-exe** [comment]
can i get assigned

**Comment by pratham-exe** [comment]
can i get assigned

**Comment by Shriya285** [comment]
can i get assigned?

**Comment by 7Akshu77** [comment]
Can I get assigned to this issue

**Comment by Advaith-RN** [comment]
@PandaTGOS Have assigned the issue to you.

**Comment by Advaith-RN** [comment]
@PandaTGOS please confirm or it will be assigned to the next person

**Comment by Lohithsurya** [comment]
can i get assigned to this issue

**Comment by Advaith-RN** [comment]
> can i get assigned to this issue

Sure

have assigned it

**Comment by PandaTGOS** [comment]
Sorry was working on another issue

**Comment by PandaTGOS** [comment]
Can I get assigned next ?

**Comment by Advaith-RN** [comment]
Sure ill assign rn

**Comment by PandaTGOS** [comment]
K on it

**Comment by SafwanAhmed08** [comment]
can i get assigned to this

**Comment by Advaith-RN** [comment]
@PandaTGOS @Lohithsurya progress check?

**Comment by 411sst** [comment]
can i get assigned if this is still open?

**Comment by Advaith-RN** [comment]
@ssether04 assigned

**Comment by Samantha-Susan-John** [comment]
Can i do this?

**Comment by amankhandelwaal** [comment]
hey, can i get assigned to this #1

**Comment by avdhagam** [comment]
hey can I get assigned to this
