### ISSUE TITLE
Add user flow to add items to a user's cart

### ISSUE THREAD

**Issue by Advaith-RN** [acmpesuecc/hyper-soar#2]
Currently, the site is a basic infographic, presenting users with items. Add a cart option in the front end, to allow the user to to add items to cart and track their purchase.

 - Ensure you plan the user flow, and get it approved by the maintainer before proceeding with the code.
 - It is recommended that you tackle this issue along with connecting it to the server.

### Maintainer Name
Advaith Rajan Nair

**Comment by PandaTGOS** [comment]
Can I get assigned to this ?

**Comment by Drakonxd786** [comment]
Can i get assigned this issue?

**Comment by sid-nc** [comment]
can i get assigned

**Comment by Advaith2805** [comment]
can i get assigned

**Comment by Advaith-RN** [comment]
> Can I get assigned to this ?

@PandaTGOS Have assigned to you.

**Comment by Advaith-RN** [comment]
@Advaith2805 @Drakonxd786 @sid-nc which one of you is up for this?

**Comment by Drakonxd786** [comment]
I am @Advaith-RN  please do give me this.

**Comment by Advaith-RN** [comment]
> I am @Advaith-RN please do give me this.

assigned @Drakonxd786

**Comment by Drakonxd786** [comment]
@Advaith-RN  Thank you

**Comment by Drakonxd786** [comment]
@Advaith-RN could you please assign this issue to someone else as i am facing some issues in regards to Yarn installation

**Comment by Advaith-RN** [comment]
@Drakonxd786 need help with the install?

**Comment by Drakonxd786** [comment]
@Advaith-RN sorry i switched to an easier task

**Comment by Advaith-RN** [comment]
@PandaTGOS @sid-nc this issue is open. lmk if you wanna work on it

**Comment by akdino** [comment]
can i get assigned to this pls?

**Comment by Advaith-RN** [comment]
ok @akdino if you have any doubts ill be in the maintainers room 001

**Comment by Lohithsurya** [comment]
can i get assigned to it

**Comment by 411sst** [comment]
can i get assigned if this is still open?

**Comment by Lohithsurya** [comment]
can i have this issue pls

**Comment by Advaith-RN** [comment]
@Lohithsurya any issues?
