### ISSUE TITLE
About Us page requires redesign

### ISSUE THREAD

**Issue by Advaith-RN** [acmpesuecc/hyper-soar#3]
This repo uses tailwind-css. Redesign the About Us section to make it both responsive and more attractive to the user. You may add more information to the info-cards.

_**Ensure that you confirm the design with the maintainer before you proceed to code it out!**_ 

A better design may get you bonus bounty points.

### Maintainer Name
Advaith Rajan Nair

**Comment by NereidaRondon** [comment]
Hi @Advaith-RN, can I give this issue a try, please?

**Comment by shreyahegde26** [comment]
can i get assigned this?

**Comment by ShankyTaco** [comment]
Please assign me this issue!

**Comment by Archit-Rode** [comment]
Hey can i get assigned to this

**Comment by Drakonxd786** [comment]
can i get assigned this issue?

**Comment by sid-nc** [comment]
can i get assigned

**Comment by nik2203** [comment]
Hi, can I be assigned to this issue?

**Comment by icantype1912** [comment]
This is a issue that i rly want to work on and try my hand in and would love it if u can assign this to me(not kissing your ass btw)

**Comment by 7Akshu77** [comment]
Can I get assigned to this issue

**Comment by Advaith-RN** [comment]
@shreyahegde26 have assigned to you, please confirm the layout with me before you proceed to code it out. I'll be in the maintainer's room 001.

**Comment by Advaith-RN** [comment]
@shreyahegde26 please confirm if you are taking up the issue

**Comment by Advaith-RN** [comment]
@ShankyTaco @nik2203 @Arty1912 @7Akshu77 which one of you is up for this?

**Comment by nik2203** [comment]
I'm up for this

**Comment by Advaith-RN** [comment]
> I'm up for this

Cool. Have assigned @nik2203

**Comment by Advaith-RN** [comment]
Ensure you plan out the layout and show it to me @nik2203. LMK if you need any more clarification.

**Comment by nik2203** [comment]
> Ensure you plan out the layout and show it to me @nik2203. LMK if you need any more clarification.
> 

Sure. You'll be in 001 right? I'll come there to show you the redesign once I'm done w it

**Comment by Advaith-RN** [comment]
yes

**Comment by Alley2717** [comment]
is this available? can i try

**Comment by Advaith-RN** [comment]
@nik2203 progress check?

**Comment by Advaith-RN** [comment]
@Alley2717 you can start designing the layout.

**Comment by nik2203** [comment]
> @nik2203 progress check?
> 

almost done i'll come to 001 in 5-10 mins and show you

**Comment by Advaith-RN** [comment]
Cool

**Comment by Advaith-RN** [comment]
@Alley2717 have unassigned you for now, a lot of the other issues on this repo have also opened up. Do consider attempting those.

**Comment by 411sst** [comment]
can i get assigned if this is still open?

**Comment by 7Akshu77** [comment]
can I get assigned to this issue

**Comment by nik2203** [comment]
@Advaith-RN got the carousel roughly working, needs polishing. could you come to sem hall 2?

**Comment by Advaith-RN** [comment]
Is it looking fine now?
