### ISSUE TITLE
Add a MongoDB route to authenticate users in the back-end

### ISSUE THREAD

**Issue by Advaith-RN** [acmpesuecc/hyper-soar#4]
A slightly bigger issue, this requires you to add a basic route that can authenticate users, instead of the front-end auth being done currently.

Ensure that this auth setup can be configured, as you can stack other issues in this repo, namely the "Add to cart" enhancement, and connect it to the back-end.

_Bonus points if you attempt both issues._

### Maintainer Name
Advaith Rajan Nair

**Comment by dishashrivas1ava** [comment]
please assign this to me

**Comment by Advaith-RN** [comment]
@dishashrivas1ava assigned

**Comment by Advaith-RN** [comment]
@dishashrivas1ava progress check? ran into any issues?

**Comment by 411sst** [comment]
can i get assigned if this is still open?

**Comment by Advaith-RN** [comment]
Sure @ssether04  make sure to meet me in the maintainers room before you begin

**Comment by Samantha-Susan-John** [comment]
Can i work on this?

**Comment by Samantha-Susan-John** [comment]
Can i be assigned to this?
